# Generated by Django 5.1.4 on 2025-01-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('num_in_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_warning', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(help_text='Format: AB-A-5', max_length=10)),
            ],
        ),
    ]
