# Generated by Django 5.1.4 on 2025-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('ready', 'Ready for Collection'), ('collected', 'Collected')], default='in_progress', max_length=50),
        ),
    ]
